SAPHanaSR-upgrade-to-angi-demo: xmllint

diff --git a/test/SAPHanaSR-upgrade-to-angi-demo b/test/SAPHanaSR-upgrade-to-angi-demo
--- a/test/SAPHanaSR-upgrade-to-angi-demo
+++ b/test/SAPHanaSR-upgrade-to-angi-demo
@@ -11,12 +11,11 @@
 #
 # define parameters and functions 
 #
-
 VERSION="2024-03-08 0.1"
-
 DRYRUN=yes
 EXE=$(basename $0)
 TMP=/run/$EXE.$RANDOM
+ALL_RC=0
 
 # TODO how to use templates from package SAPHanaSR-angi? 
 CIB_MSTTMP_ANG="#
@@ -75,7 +74,7 @@ function wait-idle() {
 
 function init-variables() {
 	mkdir -p -m 700 $TMP || exit 1
-	cibadmin -Ql > $TPM/cibtmp || exit 1
+	cibadmin -Ql > $TMP/cibtmp || exit 1
 	SCRIPT=/usr/bin/$EXE
 	TIMEST=$(date +%s)
 	BAKDIR=/root/${EXE}.$TIMEST
@@ -87,30 +86,36 @@ function init-variables() {
 		awk '{print $6}')
 	sid=${SID,,}
 	sidadm=${sid}adm
-	# xmllint -xpath "string(///resources//*[@type='SAPHana']/instance_attributes/nvpair[@name='SID'][@value='HA1']/../../../@id)" $TMP/cibtmp
-	MSTOLD=$(SAPHanaSR-showAttr --format script |\
-	       	awk -F"/" '$1~/Resource/ && $2~/ms.*'$SID'/ && $3~/maintenance=/ {print $2}')
-	# xmllint -xpath "string(///resources//*[@type='SAPHana']/@id)" $TMP/cibtmp
-	RSCCON=$(crm configure show type:clone |\
-	       	awk '$1=="clone" && $2=="'$MSTOLD'" {print $3}')
+	MSTOLD=$(xmllint -xpath \
+		"string(///resources//*[@type='SAPHana']/instance_attributes/nvpair[@name='SID'][@value='$SID']/../../../@id)" $TMP/cibtmp)
+	# MSTOLD=$(SAPHanaSR-showAttr --format script |\
+	#      	awk -F"/" '$1~/Resource/ && $2~/ms.*'$SID'/ && $3~/maintenance=/ {print $2}')
+	RSCCON=$(xmllint -xpath "string(///resources//*[@type='SAPHana']/@id)" $TMP/cibtmp)
+	# RSCCON=$(crm configure show type:clone |\
+	#      	awk '$1=="clone" && $2=="'$MSTOLD'" {print $3}')
 	MSTNEW=mst_SAPHanaCon_${SID}_HDB${INO}
-	CLNTOP=$(crm configure show type:order |\
-	       	awk '$1=="order" && $5=="'$MSTOLD'" {print $4}')
-	# xmllint -xpath "string(///resources//*[@type='SAPHanaTopology']/@id)" $TMP/cibtmp
-	RSCTOP=$(crm configure show type:clone |\
-	       	awk '$1=="clone" && $2=="'$CLNTOP'" {print $3}')
+	CLNTOP=$(xmllint -xpath \
+		"string(///resources//*[@type='SAPHanaTopology']/instance_attributes/nvpair[@name='SID'][@value='$SID']/../../../@id)" $TMP/cibtmp)
+	# CLNTOP=$(crm configure show type:order |\
+	#      	awk '$1=="order" && $5=="'$MSTOLD'" {print $4}')
+	RSCTOP=$(xmllint -xpath "\
+		string(///resources//*[@type='SAPHanaTopology']/@id)" $TMP/cibtmp)
+	# RSCTOP=$(crm configure show type:clone |\
+	#      	awk '$1=="clone" && $2=="'$CLNTOP'" {print $3}')
 	# xmllint -xpath "string(///resources//*[@type='SAPHanaTopology']/instance_attributes/nvpair[@name='SID'][@value='HA1']/../../../@id)" $cibtmp
-	# xmllint -xpath "string(///resources//*[@type='SAPHanaTopology']/../@id)" $TMP/cibtmp
 	CLNNEW=cln_SAPHanaTop_${SID}_HDB${INO}
-	# xmllint -xpath "string(///constraints//*[@then='mst_SAPHana_HA1_HDB00']/@id)" $TMP/cibtmp
-	MSTORD=$(crm configure show type:order |\
-		awk '$1=="order" && $4=="'$CLNTOP'" && $5=="'$MSTOLD'" {print $2}')
-	# xmllint -xpath "string(///constraints//*[@with-rsc='mst_SAPHana_HA1_HDB00']/@id)" $TMP/cibtmp
-	MSTCOL=$(crm configure show type:colocation |\
-		awk '$1=="colocation" && $5=="'$MSTOLD':Master" {print $2}')
-	# xmllint -xpath "string(///constraints//*[@with-rsc='mst_SAPHana_HXE_HDB90']/@rsc)" $TMP/cibtmp
+	MSTORD=$(xmllint -xpath \
+		"string(///constraints//*[@then='$MSTOLD']/@id)" $TMP/cibtmp)
+	# MSTORD=$(crm configure show type:order |\
+	#	awk '$1=="order" && $4=="'$CLNTOP'" && $5=="'$MSTOLD'" {print $2}')
+	MSTCOL=$(xmllint -xpath \
+		"string(///constraints//*[@with-rsc='$MSTOLD']/@id)" $TMP/cibtmp)
+	# MSTCOL=$(crm configure show type:colocation |\
+	#	awk '$1=="colocation" && $5=="'$MSTOLD':Master" {print $2}')
+	# TODO RSCIPA=$(xmllint ...)
 	RSCIPA=$(crm configure show type:colocation |\
-		awk '$1=="colocation" && $5=="'$MSTOLD':Master" {print $4}' | awk -F: '{print $1}')
+		awk '$1=="colocation" && $5=="'$MSTOLD':Master" {print $4}' |\
+		awk -F: '{print $1}')
 	PRINOD=$(SAPHanaSR-showAttr --format script |\
 	       	awk -F"/" '$1~/Host/&&$3=="score=\"150\"" {print $2}')
 	SECNOD=$(SAPHanaSR-showAttr --format script |\
@@ -175,7 +180,7 @@ function f_show-state() {
 	echo-funa end $FUNCNAME
 }
 
-function f_old-maintenance-on() {
+function f_maintenance-on-angi() {
 	echo-funa run $FUNCNAME
 	wait-idle
 	echo "crm resource maintenance $MSTOLD on"
@@ -187,7 +192,7 @@ function f_old-maintenance-on() {
 	echo-funa run $FUNCNAME
 }
 
-function f_new-maintenance-off() {
+function f_maintenance-off-classic() {
 	echo-funa run $FUNCNAME
 	wait-idle
 	echo "crm resource refresh $CLNTOP"
@@ -227,7 +232,7 @@ function del-srhook-local() {
 
 function f_remove-srhook-classic() {
 	echo-funa run $FUNCNAME
-	crm cluster run "/usr/bin/'$EXE' --run del-srhook-local"
+	crm cluster run "'$SCRIPT' --run del-srhook-local"
 	echo-funa end $FUNCNAME
 }
 
@@ -248,7 +253,7 @@ function add-srhook-local() {
 
 function f_add-srhook-angi() {
         echo-funa run $FUNCNAME
-        crm cluster run "/usr/bin/'$EXE' --run add-srhook-local"
+        crm cluster run "'$SCRIPT' --run add-srhook-local"
         echo-funa end $FUNCNAME
 }
 
@@ -351,13 +356,13 @@ function f_check-prereqs() {
 	        pre_rc=9
 	fi
 	if [ $HOSTNAME != $PRINOD ]; then
-	        echo "ERROR: Not running on primary node."
+	        echo "ERROR: Looks not like primary node."
 	        pre_rc=9
 	fi
 	my_vers=$($SCRIPT -v)
 	ssh root@${SECNOD} "'$SCRIPT' -v" | grep "$my_vers" >/dev/null; my_rc=$?
 	if [ $my_rc != 0 ]; then
-        	echo "ERROR: Can not access ${SECNOD}."
+        	echo "ERROR: Can not call $SCRIPT on  ${SECNOD}."
         	pre_rc=9
 	fi
 	if [ ! -r $SUDOER ]; then
@@ -395,6 +400,7 @@ function f_check-prereqs() {
 		exit $pre_rc
 	fi
 	show-variables
+	ALL_RC=$pre_rc
 	echo "RC=$pre_rc"
 	echo-funa end $FUNCNAME
 }
@@ -420,6 +426,8 @@ function show-help() {
 	echo " --check-prereqs"
 	echo " --upgrade"
 	echo
+	echo "SAPHanaSR-upgrade-to-angi-demo is shipped as technology preview."
+	echo
 }
 
 function upgrade-to-angi() {
@@ -430,7 +438,7 @@ function upgrade-to-angi() {
 	# make backup of some config
 	f_make-backup
 	# set HANA classic resources to maintenance
-	f_old-maintenance-on
+	f_maintenance-on-classic
 	# remove SAPHanaSR.py from global.ini, HANA, and sudoer
 	f_remove-srhook-classic
 	# remove HANA classic resource config from CIB
@@ -446,7 +454,7 @@ function upgrade-to-angi() {
 	f_add-saphanacon-angi
 	f_add-sapfilesystem
 	# set HANA angi resource out of maintenance
-	f_new-maintenance-off
+	f_maintenance-off-angi
 	# check for sane state
 	f_check-state
 	# test RA on secondary and trigger susHanaSR.py
@@ -457,7 +465,7 @@ function test(){
 	f_check-prereqs
 	f_show-state
 	f_make-backup
-	f_old-maintenance-on
+	f_maintenance-on-classic
 	f_remove-srhook-classic
 	f_remove-saphanacon-classic
 	f_remove-property
@@ -466,7 +474,7 @@ function test(){
 	f_add-saphanacon-angi
 	f_add-sapfilesystem
 	f_add-srhook-angi
-	f_new-maintenance-off
+	f_maintenance-off-angi
 	#f_show-state
 }
 
@@ -491,9 +499,7 @@ case $1 in
 	;;
 	-u | --upgrade)
 		init-variables
-		show-variables
-		# upgrade-to-angi
-		echo "nop"
+		upgrade-to-angi
 	;;
 	-r | --run | --run-fun*)
 		init-variables
@@ -506,6 +512,6 @@ case $1 in
 		show-help
 	;;
 esac
-rm $TMP/* 2>/dev/null; rmdir $TMP 2>/dev/null
-exit
+rm -f $TMP/*; rmdir $TMP
+exit $ALL_RC
 #
