SAPHanaSR-upgrade-to-angi-demo: prereqs

diff --git a/test/SAPHanaSR-upgrade-to-angi-demo b/test/SAPHanaSR-upgrade-to-angi-demo
--- a/test/SAPHanaSR-upgrade-to-angi-demo
+++ b/test/SAPHanaSR-upgrade-to-angi-demo
@@ -416,6 +416,24 @@ function f_check-prereqs() {
 	        echo "ERROR: Looks not like primary node."
 	        pre_rc=9
 	fi
+	os_vers=$(grep "PRETTY_NAME=\"SUSE Linux Enterprise Server 15 SP[4-7]\"" /etc/os-release \
+		>/dev/null 2>&1; echo $?)
+	if [ ! $os_vers != 0 ]; then
+	        echo "ERROR: Local OS version is not supported."
+	        pre_rc=9
+	fi
+	hana_rev=$(su - $sidadm -c "HDB version" | awk -F: '$1=="  version" {print $2}' | tr -d ".")
+	if [ ! $hana_rev -ge 200059040000000000 ]; then
+	        echo "ERROR: Local HANA revision looks like not supported."
+	        pre_rc=9
+	fi
+
+	hana_py=$(su - $sidadm -c "python --version" | grep "Python 3\.[7-9]" \
+		>/dev/null 2>&1; echo $?)
+	if [ ! $hana_py != 0 ]; then
+	        echo "ERROR: Local HANA python looks like not supported."
+	        pre_rc=9
+	fi
 	ssh root@$SECNOD "'$SCRIPT' -v" | grep "$VERSION" >/dev/null; my_rc=$?
 	if [ $my_rc != 0 ]; then
         	echo "ERROR: Can not call $SCRIPT on ${SECNOD}."
@@ -509,8 +527,8 @@ function show-help() {
 }
 
 function upgrade-to-angi() {
-	# prepare environment for script
-	f_check-prereqs
+	# TODO prepare environment for script?
+	#f_check-prereqs
 	# check for sane state
 	f_show-state
 	# make backup of some config
@@ -545,26 +563,6 @@ function upgrade-to-angi() {
 
 function cleanup() {
 	crm cluster run "rm -f /run/$EXE.variables >/dev/null 2>&1"
-}
-
-function test(){
-	f_check-prereqs
-	f_show-state
-	f_make-backup
-	f_maintenance-on-classic
-	f_remove-srhook-classic
-	f_remove-saphanacon-classic
-	f_remove-property
-	f_remove-node-attribute
-	f_update-rpm
-	f_add-srhook-angi
-	f_add-saphanacon-angi
-	f_add-sapfilesystem
-	f_maintenance-off-angi
-	f_show-state
-	f_check-final-state
-	f_test-secondary
-	f_show-state
 }
 
 #
