test/SAPHanaSR-replay-archive: adding option --pengine to allow pengine directories (instead of archives)

diff --git a/test/SAPHanaSR-replay-archive b/test/SAPHanaSR-replay-archive
--- a/test/SAPHanaSR-replay-archive
+++ b/test/SAPHanaSR-replay-archive
@@ -33,6 +33,10 @@ while [ $# -gt 0 ]; do
      --help|-h)
         echo
         echo "usage:    $bex [--format=script] /path/to/pe-archive (tar.bz2)"
+        echo "usage:    $bex [--format=script] --pengine=/path/to/pengine-files"
+        echo
+        echo "Possible output formats: tables, script, book"
+        echo "For format 'book' there is also an optional parameter --outDir"
         echo
         echo "usage:    $bex [OPTION]"
         echo " --help		show help."
@@ -50,6 +54,10 @@ while [ $# -gt 0 ]; do
         --outDir=* )
             outDir=${1#*=}
     ;;
+        --pengine=* )
+            pengine=${1#*=}
+	    echo "pengine directory $pengine"
+    ;;
         * )
         archive="$1"
     ;;
@@ -61,9 +69,15 @@ done
 ####################
 #
 #
-mkdir -p "${archive}-tmp"
-if ! tar -xjf "$archive" -C "${archive}-tmp" ; then echo "Extracting archive $archive failed"; exit 2; fi
-if ! cd "${archive}-tmp"; then echo "Can not enter archive directory ${archive}-tmp"; exit 2; fi
+if [ -z "$pengine" ]; then
+	echo "pengine is not set"
+    mkdir -p "${archive}-tmp"
+    if ! tar -xjf "$archive" -C "${archive}-tmp" ; then echo "Extracting archive $archive failed"; exit 2; fi
+    if ! cd "${archive}-tmp"; then echo "Can not enter archive directory ${archive}-tmp"; exit 2; fi
+else
+	echo "pengine is set"
+        cd $pengine; cd ..
+fi
 #
 ####################
 #
@@ -108,7 +122,13 @@ done | sort -u | tr '[:upper:]' '[:lower:]' )
 #
 # create a tmp directory to extract pengine files
 #
-mkdir -p "${archive}-tmp/tmp"
+if [ -z "$pengine" ]; then
+    mkdir -p "${archive}-tmp/tmp"
+    pengine_tmp="${archive}-tmp/tmp"
+else
+    mkdir -p "${pengine}-tmp"
+    pengine_tmp="${pengine}-tmp"
+fi
 #
 ####################
 # create output directory, if set
@@ -138,17 +158,17 @@ for sid in $sids; do
        bunzip2 -c "$cibBZ2" > "${archive}-tmp/tmp/$shortCIB";
        case "$format" in
            tables | script )
-               /usr/sbin/SAPHanaSR-showAttr --cib="${archive}-tmp/tmp/$shortCIB" --sid="$sid" --format="$format";
+               /usr/sbin/SAPHanaSR-showAttr --cib="$cibFile" --sid="$sid" --format="$format";
                    ;;
            book )
                if [ -n "$outDir" ]; then
                    outOption="--out=$outDir/sapMonitor.$outNr.html"
                    (( outNr ++ ))
                fi
-               /usr/sbin/SAPHanaSR-monitor --cib="${archive}-tmp/tmp/$shortCIB" --sid="$sid" --format="html2" "$outOption";
+               /us/sbin/SAPHanaSR-monitor --cib="$cibFile" --sid="$sid" --format="html2" "$outOption";
                    ;;
            txt | ascii | html )
-               /usr/sbin/SAPHanaSR-monitor --cib="${archive}-tmp/tmp/$shortCIB" --sid="$sid" --format="$format"
+               /usr/sbin/SAPHanaSR-monitor --cib="$cibFile" --sid="$sid" --format="$format"
                    ;;
        esac
        rm "${archive}-tmp/tmp/$shortCIB" ;
