angi step 23: test-lib: implement cleanup action (currently static - TODO: get resource name by JSON file)

diff --git a/test/test-lib b/test/test-lib
--- a/test/test-lib
+++ b/test/test-lib
@@ -324,6 +324,15 @@ function action {
            timeout 10 ssh "$node" 'su - '"$sidadm"' -c "HDB kill-9" 2>/dev/null 1>/dev/null' rc="$?"
            message "ACTION: HDB kill-9 on node $node rc=$rc"
            ;;
+      cleanup ) # cleanup cluster resource 
+           local sidadm="ha1adm"
+           local node="$pHost"
+           local resource="ms_SAPHanaCon_HA1_HDB00"
+           local rc=0
+           message "ACTION: crm cleanup resource $resource"
+           timeout 10 ssh "$node" 'crm resource cleanup '"$resource"' '; rc="$?"
+           message "ACTION: crm cleanup resource $resource rc=$rc"
+           ;;
    esac
    return "$rc"
 }
