tester: runtest

diff --git a/test/samples/runtest b/test/samples/runtest
--- a/test/samples/runtest
+++ b/test/samples/runtest
@@ -1,22 +1,25 @@
 #!/bin/bash
 # runtests
-# 2024-07-04
-
-PROPERTIES="./properties_angi-ScaleOut_hoeferspitze.json"
+#
+# (c) 2024-2025 SUSE LLC
+# Author: F.Herschel, L.Pinne.
+# GNU General Public License v2. No warranty.
+# http://www.gnu.org/licenses/gpl.html
+#
+# Version: 2025-02-25
+#
+PROPERTIES="./properties_angi-ScaleOut.json"
 REMOTENODES="hoeferspitze11 hoeferspitze21"
 ASTROOT=/usr/share/SAPHanaSR-tester/json/angi-ScaleOut
 LOGFILE="runtests.log"
 
+source /usr/share/SAPHanaSR-tester/samples/runtests_angi-ScaleOut_conservative.txt
+
 exec 3>&1
 exec 1>>"$LOGFILE"
 
-SECNCAS="kill_secn_inst kill_secn_indexserver kill_secn_node standby_secn_node standby_secn_worker_node free_log_area"
-PRIMCAS="kill_prim_inst kill_prim_worker_inst kill_prim_indexserver kill_prim_node kill_prim_worker_node freeze_prim_master_nfs standby_prim_node"
-BOTHCAS="restart_cluster restart_cluster_hana_running restart_cluster_turn_hana maintenance_cluster_turn_hana maintenance_with_standby_nodes nop"
-
-#TCASES="flup kill_prim_node_fencing_alert kill_prim_worker_node_fencing_alert free_log_area"
-TCASES="flup kill_prim_node free_log_area kill_prim_worker_node free_log_area"
-#TCASES="flup free_log_area $SECNCAS $PRIMCAS free_log_area $BOTHCAS free_log_area"
+# TCASES="flup free_log_area $SECNCAS free_log_area $PRIMCAS free_log_area $BOTHCAS free_log_area"
+TCASES="flup kill_prim_node free_log_area"
 
 for TEST in $TCASES; do
   echo "#### $(date +%Y-%m-%d" "%H:%M:%S) run test: $TEST ####"
@@ -25,10 +28,11 @@ for TEST in $TCASES; do
     hana_fill=$(ssh $N "df --output=pcent $hana_fs | grep -v Use")
     echo "$(date +%Y-%m-%d\ %H:%M:%S) fill grade: $N $hana_fs $hana_fill"
   done
-  SAPHanaSR-testCluster --testFile "$ASTROOT/$TEST.json" \
+  SAPHanaSR-testCluster --testFile "$ASTROOT/$TEST.json" --properties "$PROPERTIES" \
                         --remoteNodes $REMOTENODES --defaultsFile "$ASTROOT/defaults.json" \
-                        --logFile "$TEST.log" --properties "$PROPERTIES" --dumpFailures >&3; rc=$?
+                        --logFile "$TEST.log" --jsonOut "$TEST.json.out" --dumpFailures >&3; rc=$?
   echo "#### $(date +%Y-%m-%d" "%H:%M:%S) end test: $TEST rc: $rc ####"
+  gzip -g "$TEST.json.out"
   if [[ "$rc" != "0" ]]; then
     exit 1
   else
