angi step 16: SAPHanaTopology could now be completely shellcheked calling: shellcheck -a -x SAPHanaController; to allow this shellcheck disable-directives have been added as shell-comments on code lines intended not to be checked with standard rules

diff --git a/ra/saphana-topology-lib b/ra/saphana-topology-lib
--- a/ra/saphana-topology-lib
+++ b/ra/saphana-topology-lib
@@ -28,6 +28,11 @@ saphana_topology_lib_version="1.001.3"
 #
 #######################################################################
 
+function sht_log_version()
+{
+    super_ocf_log info "RA: saphana_topology_lib_version=$saphana_topology_lib_version"
+}
+
 #
 # function: sht_usage - short usage info
 # params:   -
@@ -37,7 +42,7 @@ function sht_usage() {
     super_ocf_log info "FLOW ${FUNCNAME[0]} ($*)"
     local rc=0
     methods=$(sht_methods all)
-    methods=$(echo $methods | tr ' ' '|')
+    methods="${methods// /|}"
   cat <<-!
 	usage: $0 ($methods)
 
@@ -53,7 +58,7 @@ function sht_usage() {
     The 'reload'       operation allows to change parameters like HANA_CALL_TIMEOUT without forcing a recover of all instances
 
 	!
-	return $rc
+	return "$rc"
 }
 
 #
@@ -62,7 +67,7 @@ function sht_usage() {
 # globals:  -
 #
 function sht_meta_data() {
-    super_ocf_log info "FLOW ${FUNCNAME[0]} ($*)"
+    super_ocf_log info "FLOW ${FUNCNAME[0]} ()"
     local rc=0
 	cat <<END
 <?xml version="1.0"?>
@@ -135,7 +140,7 @@ SAPHanaTopology scans the output table of landscapeHostConfiguration.py to ident
 </actions>
 </resource-agent>
 END
-return $rc
+return "$rc"
 }
 
 #
@@ -157,8 +162,9 @@ function sht_methods() {
             methods="start stop status monitor reload"
             ;;
     esac
-    printf "%s " $methods
-    return $rc
+    # shellcheck disable=SC2086
+    printf "%s " $methods   # unquoted "methods" is intended here ( ##shellcheck disabled for this line)
+    return "$rc"
 }
 
 #
@@ -177,25 +183,25 @@ function sht_init() {
     local myInstanceName=""
     local rc=$OCF_SUCCESS
     local hdbANSWER=""
-    local siteID
     local siteNAME
     local chkMethod=""
+    # TODO PRIO3: NG - some vars are marked for export to avoid 'unused' error in shellcheck. Check later, if these vars are valuable again when combining Topology and Controller in the next step
     SYSTEMCTL="/usr/bin/systemctl"
     systemd_unit_name="saphostagent.service"
     HOSTEXECNAME=saphostexec
     USRSAP=/usr/sap
-    SAPSERVICE_PATH=${USRSAP}/sapservices
+    export SAPSERVICE_PATH=${USRSAP}/sapservices
     SAPHOSTCTRL_PATH=${USRSAP}/hostctrl/exe
     HOSTEXEC_PATH=${SAPHOSTCTRL_PATH}/${HOSTEXECNAME}
     HOSTEXEC_PROFILE_PATH=${SAPHOSTCTRL_PATH}/host_profile
     NODENAME=$(crm_node -n)
     SID=$OCF_RESKEY_SID
     InstanceNr=$OCF_RESKEY_InstanceNumber
-    myInstanceName="${SID}_HDB${InstanceNr}"
+    export myInstanceName="${SID}_HDB${InstanceNr}"
     InstanceName="HDB${InstanceNr}"
     HANA_CALL_TIMEOUT="${OCF_RESKEY_HANA_CALL_TIMEOUT:-120}"
     sid="${SID,,}"
-    sidadm="${sid}adm"
+    export sidadm="${sid}adm"     # TODO PRIO3: NG - check if we use that var in a Topology/Controller common function in future
     #ocf_env=$(env | grep 'OCF_RESKEY_CRM')
     #super_ocf_log debug "DBG: OCF: $ocf_env"
     #
@@ -224,9 +230,9 @@ function sht_init() {
 
     if [ -z "$OCF_RESKEY_DIR_PROFILE" ]
     then
-        DIR_PROFILE="/usr/sap/$SID/SYS/profile"
+        export DIR_PROFILE="/usr/sap/$SID/SYS/profile"  # TODO PRIO3: NG - check if we use that var in a Top/Con common variable
     else
-        DIR_PROFILE="$OCF_RESKEY_DIR_PROFILE"
+        export DIR_PROFILE="$OCF_RESKEY_DIR_PROFILE"
     fi
 
     #PATH=${PATH}:${DIR_EXECUTABLE}
@@ -247,6 +253,8 @@ function sht_init() {
     [[ -z ${ges_ver:-} ]] && ges_ver=$(HANA_CALL --timeout 10 --cmd "HDB version" | tr -d " " | awk -F: '$1 == "version" {print $2}')
     #Version xx.yy.zzz
     [[ ${ges_ver} =~ [0-9]+(\.[0-9]+){2} ]] && hdbver=${BASH_REMATCH[0]}
+    # TODO PRIO2: NG - use function instead of code here
+    super_ocf_log info "DEC: SAP HANA version $hdbver"
 
     hdbState="hdbnsutil -sr_stateConfiguration"
     hdbMap="hdbnsutil -sr_stateHostMapping"
@@ -289,7 +297,7 @@ function sht_init() {
         esac
     done
     # TODO PRIO3: Implement a file lookup, if we did not get a result
-    siteID=$(echo "$hdbANSWER" | awk -F= '/site.id/ {print $2}')       # allow 'site_id' AND 'site id'
+    #siteID=$(echo "$hdbANSWER" | awk -F= '/site.id/ {print $2}')       # allow 'site_id' AND 'site id'
     siteNAME=$(echo "$hdbANSWER" | awk -F= '/site.name/ {print $2}')
     site=$siteNAME
     # from scale-up: only set srmode, if it is still empty
@@ -306,7 +314,7 @@ function sht_init() {
     # TODO PRIO2: NG - do we still need the 'remoteHost' - is the remoteMNS sufficient instead?
     #
     hdbANSWER=$(HANA_CALL --timeout "$HANA_CALL_TIMEOUT" --cmd "$hdbMap --sapcontrol=1" 2>/dev/null)
-    srRemoteHosts=$(echo "$hdbANSWER" | awk -F[=/] '$1 == "mapping" && $2 == myhost && $3 != site { print $4 }' site=$site myhost=$HOSTNAME)
+    srRemoteHosts=$(echo "$hdbANSWER" | awk -F[=/] '$1 == "mapping" && $2 == myhost && $3 != site { print $4 }' site="$site" myhost="$HOSTNAME")
     # TODO PRIO2: NG - super_ocf_log: re-classify the log classes (here new class 'INFO?'
     super_ocf_log debug "INFO: site=$site, mode=$srmode, srRemoteHosts=$srRemoteHosts"
     #
@@ -361,7 +369,7 @@ function sht_init() {
     fi
     ########### END SCALE OUT CODE
     super_ocf_log info "FLOW ${FUNCNAME[0]} rc=$OCF_SUCCESS"
-    return $OCF_SUCCESS
+    return "$OCF_SUCCESS"
 }
 
 #
@@ -375,14 +383,14 @@ function sht_init() {
 function sht_start() {
     super_ocf_log info "FLOW ${FUNCNAME[0]} ()"
 
-    local rc=$OCF_NOT_RUNNING
+    local rc="$OCF_NOT_RUNNING"
     local output=""
-    local loopcount=0
+    #local loopcount=0
 
     # TODO: PRIO3: move the string "$HA_RSCTMP/SAPHana/SAPTopologyON" to a variable
     # TODO: PRIO3: move the file to the clusters tmp directory?
-    mkdir -p $HA_RSCTMP/SAPHana
-    touch $HA_RSCTMP/SAPHana/SAPTopologyON.${SID}
+    mkdir -p "$HA_RSCTMP/SAPHana"
+    touch "$HA_RSCTMP/SAPHana/SAPTopologyON.${SID}"
     if ! check_saphostagent; then
         start_saphostagent
     fi
@@ -390,14 +398,14 @@ function sht_start() {
     # currently using the always-good mode to force OCF_SUCCESS
     RC_hdbnsutil=0
     case "$RC_hdbnsutil" in
-        0 | 1 ) rc=$OCF_SUCCESS;;     # TODO: Prio 3: Need to check rc==1 - is that success or not_running?
-        2 )     rc=$OCF_NOT_RUNNING;; # rc==2 have been seen for bad persistency layer
-        * )     rc=$OCF_SUCCESS;;     # TODO: Prio 3: Need to check "other" return codes
+        0 | 1 ) rc="$OCF_SUCCESS";;     # TODO: Prio 3: Need to check rc==1 - is that success or not_running?
+        2 )     rc="$OCF_NOT_RUNNING";; # rc==2 have been seen for bad persistency layer
+        * )     rc="$OCF_SUCCESS";;     # TODO: Prio 3: Need to check "other" return codes
     esac
     # old scale-up code:
     # rc=$OCF_SUCCESS
     super_ocf_log info "FLOW ${FUNCNAME[0]} rc=$rc"
-    return $rc
+    return "$rc"
 }
 
 #
@@ -410,11 +418,11 @@ function sht_stop() {
     super_ocf_log info "FLOW ${FUNCNAME[0]} ()"
     local output=""
     local rc=0
-    rm $HA_RSCTMP/SAPHana/SAPTopologyON.${SID}
-    rc=$OCF_SUCCESS
+    rm "$HA_RSCTMP/SAPHana/SAPTopologyON.${SID}"
+    rc="$OCF_SUCCESS"
 
     super_ocf_log info "FLOW ${FUNCNAME[0]} rc=$rc"
-    return $rc
+    return "$rc"
 }
 
 #
@@ -434,7 +442,7 @@ function sht_monitor() {
         rc="$OCF_NOT_RUNNING"
     fi
     super_ocf_log info "FLOW ${FUNCNAME[0]} rc=$rc"
-    return $rc
+    return "$rc"
 }
 
 #
@@ -444,11 +452,11 @@ function sht_monitor() {
 # sht_status: Lightweight check of SAP instance only with OS tools
 #
 function sht_status() {
-    super_ocf_log info "FLOW ${FUNCNAME[0]} ($*)"
+    super_ocf_log info "FLOW ${FUNCNAME[0]} ()"
     local rc=0
 
-    sht_monitor; rc=$?
-    return $rc
+    sht_monitor; rc="$?"
+    return "$rc"
 }
 
 #
@@ -506,13 +514,13 @@ function sht_stop_clone() {
     super_ocf_log info "FLOW ${FUNCNAME[0]} ($*)"
     local rc=0
     local tout=0
-    local nRole nLsc nSrmode nNsConf nNsCurr nIsConf nIsCurr
+    local nRole nNsConf 
     check_for_primary; primary_status=$?
-    if [ $primary_status -eq $HANA_STATE_PRIMARY ]; then
+    if [ "$primary_status" == "$HANA_STATE_PRIMARY" ]; then
         hanaPrim="P"
-    elif [ $primary_status -eq $HANA_STATE_SECONDARY ]; then
+    elif [ "$primary_status" == "$HANA_STATE_SECONDARY" ]; then
         hanaPrim="S"
-    elif [ $primary_status -eq $HANA_STATE_STANDALONE ]; then
+    elif [ "$primary_status" == "$HANA_STATE_STANDALONE" ]; then
         hanaPrim="N"
     else
         hanaPrim="-"
@@ -551,7 +559,7 @@ function sht_stop_clone() {
         # scale-out was: timeout of HANA_CALL, set role to '$nNsConf:shtdown:shtdown:shtdown'
         # to get the saphana_demote_clone to fail and stop the resource
         nRole=$(get_hana_attribute "${node}" "${ATTR_NAME_HANA_ROLES[@]}")
-        read -r nNsConf nNsCurr nIsConf nIsCurr <<< "${nRole//:/ }"
+        nNsConf="${nRole%%:}" # only first field use here
         set_hana_attribute "${NODENAME}" "$nNsConf:-:-:-" "${ATTR_NAME_HANA_ROLES[@]}"
         # and exit with 1 to let the stop fail
         tout=1
@@ -567,7 +575,7 @@ function sht_stop_clone() {
             $1 == "nameServerActualRole"  {nsAR=$2}
             $1 == "indexServerConfigRole" {isCR=$2}
             $1 == "indexServerActualRole" {isAR=$2}
-            END { printf "%s:%s:%s:%s\n", nsCR, nsAR, isCR, isAR;  } ' vName=$vName )
+            END { printf "%s:%s:%s:%s\n", nsCR, nsAR, isCR, isAR;  } ' vName="$vName" )
         set_hana_attribute "${NODENAME}" "$hanarole" "${ATTR_NAME_HANA_ROLES[@]}"
     fi
     sht_stop; rc=$? # till now it returns everytime $OCF_SUCCESS
@@ -588,8 +596,8 @@ function sht_monitor_clone() {
     super_ocf_log info "FLOW ${FUNCNAME[0]} ($*)"
     #
 	local rc=$OCF_ERR_GENERIC
-	local promoted=0
-    local init_attribute=0
+	#local promoted=0
+    #local init_attribute=0
 
 	if ocf_is_probe; then
 		super_ocf_log debug "DBG: PROBE ONLY"
@@ -642,7 +650,7 @@ function sht_monitor_clone() {
     #### SAP-CALL
     if [ -e /usr/sap/hostctrl/exe/saphostctrl ]; then
         vName=$(/usr/sap/hostctrl/exe/saphostctrl -function ListInstances \
-            | awk '$4 == SID && $6 == SYSNR { print $8 }' SID=$SID SYSNR=$InstanceNr 2>/dev/null )
+            | awk '$4 == SID && $6 == SYSNR { print $8 }' SID="$SID" SYSNR="$InstanceNr" 2>/dev/null )
     else
         super_ocf_log error "ERR: SAPHOSTAGENT is not installed at /usr/sap/hostctrl/exe (saphostctrl missing)"
     fi
@@ -687,9 +695,9 @@ function sht_monitor_clone() {
             $1 == "nameServerActualRole"  {nsAR=$2}
             $1 == "indexServerConfigRole" {isCR=$2}
             $1 == "indexServerActualRole" {isAR=$2}
-            END { printf "%s:%s:%s:%s\n", nsCR, nsAR, isCR, isAR;  } ' vName=$vName )
+            END { printf "%s:%s:%s:%s\n", nsCR, nsAR, isCR, isAR;  } ' vName="$vName" )
     if "$setRole"; then
-        set_hana_attribute ${NODENAME} "$hanarole" "${ATTR_NAME_HANA_ROLES[@]}"
+        set_hana_attribute "${NODENAME}" "$hanarole" "${ATTR_NAME_HANA_ROLES[@]}"
     fi
     #
     # differ between ScaleUp and ScaleOut
@@ -701,7 +709,7 @@ function sht_monitor_clone() {
                             awk -F= '
                             $1 == "host/"vName"/nameServerConfigRole"  {SoSu="ScaleOut"}
                             $1 == "nameServerConfigRole"  {SoSu="ScaleUp"}
-                            END { printf "%s\n", SoSu;  } ' vName=$vName )
+                            END { printf "%s\n", SoSu;  } ' vName="$vName" )
     set_hana_attribute "global" "$hanaScaleOutScaleUp" "${ATTR_NAME_HANA_TOPOLOGY[@]}"
     # TODO PRIO1: NG - set nodes site attribute and for the site the attributes LSS, SRR
     # TODO PRIO2: NG - COULD/SHOULD WE LIMIT THE SET OF THE LSS/SRR ATTRIBUTE TO ONLY THE_MASTER nodes?
@@ -714,7 +722,7 @@ function sht_monitor_clone() {
         set_hana_site_attribute "$site" "$hanalrc" "${ATTR_NAME_HANA_SITE_LSS[@]}"
         super_ocf_log info "DEC: set_hana_site_attribute $site $hanalrc ${ATTR_NAME_HANA_SITE_LSS[*]}"
         set_hana_site_attribute "$site" "$hanaPrim" "${ATTR_NAME_HANA_SITE_SRR[@]}"
-        set_hana_attribute ${NODENAME} "$site" "${ATTR_NAME_HANA_SITE[@]}"
+        set_hana_attribute "${NODENAME}" "$site" "${ATTR_NAME_HANA_SITE[@]}"
         super_ocf_log info "DEC: set_hana_attribute ${NODENAME} $site ${ATTR_NAME_HANA_SITE[0]}"
     fi
     case "$hanaPrim" in
@@ -736,5 +744,5 @@ function sht_monitor_clone() {
     #ATTR_NAME_HANA_STATUS  # TODO: PRIO5: For SCALE-OUT: Fill that attribute later
     fi # end ocf_is_NOT_probe
     super_ocf_log info "FLOW ${FUNCNAME[0]} rc=$rc"
-    return $rc
+    return "$rc"
 }
