Calculate a Global timeout as HANA_CALL is called multiple times.

diff --git a/ra/SAPHanaTopology b/ra/SAPHanaTopology
--- a/ra/SAPHanaTopology
+++ b/ra/SAPHanaTopology
@@ -38,6 +38,8 @@ timeB=$(date '+%s')
 #
 # Current Time
 NOW=$(date +%s)
+# Global Operation Timeout that will be used on HANA_CALL() retries
+OPERATION_TIMEOUT=$(( $NOW + ($OCF_RESKEY_CRM_meta_timeout/1000) -5 ))
 
 log_attributes=false
 if ocf_is_true "$log_attributes"; then
@@ -416,27 +418,27 @@ function HANA_CALL()
 
     case $timeout in
         0 | inf )
-                  output=$($pre_cmd "$pre_script; /usr/sap/$SID/$InstanceName/HDBSettings.sh $cmd"); rc=$?
-                  ;;
+                    output=$($pre_cmd "$pre_script; /usr/sap/$SID/$InstanceName/HDBSettings.sh $cmd"); rc=$?
+                    ;;
         *       )
-                 # In case of timeout, retries until the limit of Time configured for the RA Operation.
-                 # -5 seconds to return a treated failure before pcmk kill it.
-                 operation_timeout=$(( $NOW + ($OCF_RESKEY_CRM_meta_timeout/1000) -5 ))
-                 while [ $NOW -lt $operation_timeout ]; do
-                    output=$(timeout $timeOut $pre_cmd "$pre_script; /usr/sap/$SID/$InstanceName/HDBSettings.sh $cmd"); rc=$?
+                    # In case of timeout, retries until the limit of Time configured for the RA Operation.
+                    # -5 seconds to return a treated failure before pcmk kill it.
+                    while [ $NOW -lt $OPERATION_TIMEOUT ]; do
+                        super_ocf_log debug "NOW: $NOW Operation Timeout: $OPERATION_TIMEOUT"
+                        output=$(timeout $timeOut $pre_cmd "$pre_script; /usr/sap/$SID/$InstanceName/HDBSettings.sh $cmd"); rc=$?
 
-                    if [ $rc -eq 124 ]; then
-                      super_ocf_log warn "HANA_CALL timed out after $timeOut seconds running command '$cmd'. Retrying..."
-                    else
-                      # Successful execution. Return to the caller.
-                      super_ocf_log debug "DBG: HANA_CALL '$cmd' rc=$rc output=$output"
-                      echo "$output"
-                      return $rc;
-                    fi
+                        if [ $rc -eq 124 ]; then
+                        super_ocf_log warn "HANA_CALL timed out after $timeOut seconds running command '$cmd'. Retrying..."
+                        else
+                        # Successful execution. Return to the caller.
+                        super_ocf_log debug "DBG: HANA_CALL '$cmd' rc=$rc output=$output"
+                        echo "$output"
+                        return $rc;
+                        fi
 
-                    NOW=$(date +%s)
-                done
-			     ;;
+                        NOW=$(date +%s)
+                    done
+                    ;;
     esac
 
     # If this is executed, means that it is still timing out.
