adjusted lpa_mon's lpa algorith to use lpt-gab

diff --git a/SAPHana/lpa_mon b/SAPHana/lpa_mon
--- a/SAPHana/lpa_mon
+++ b/SAPHana/lpa_mon
@@ -68,6 +68,46 @@ function get_and_print_node()
    print_node "$node" "$node_lpt" "$node_sync" "$node_state" "$node_age" "$node_promo"
 }
 
+function lpa_check_lpt_status() {
+    local rc=0
+    local LPT0=${ALpt[0]}
+    local LPT1=${ALpt[1]}
+    local LPTDiff=0
+    #
+    # TODO: Implement lpa_check_lpt_status
+    #
+        #
+        # TODO: Maye LPA should also say win, if lpa-loc=2 and lpa-rem=1 (as special init case)
+        #
+        # TODO: We might need to fetch DUPLICATE_PRIMARY_TIMEOUT from the resource / lets
+        #       for first try default here
+        DUPLICATE_PRIMARY_TIMEOUT=7200
+        (( LPTDiff0 = LPT0 - LPT1 ))
+        (( LPTDiff1 = LPT1 - LPT0 ))
+## BAUSTELLE
+        if [ $LPTDiff0 -gt $DUPLICATE_PRIMARY_TIMEOUT ]; then
+            # We are the winner - LPA says STARTUP
+            rc=0
+        elif [ $LPTDiff1 -gt $DUPLICATE_PRIMARY_TIMEOUT ]; then
+            # The other one has won - LPA says REGISTER
+            rc=1
+        else
+            if [ $LPT0 -eq 1 ]; then
+                # TODO: Do we need to differ between a 1=1 with different sync status?
+                # This case can happen: a) when really to secondaries would in the cluster 
+                #                       b) when a primary failed and restarts with prefrred remote takeover 
+                #                        
+                rc=2
+            else
+                # THIS IS A STALEMATE, WHICH COULD HAPPEN
+                # TODO: CHeck, if FAIL is the correct behaviour - or just wait for admin to decide via attribute?
+                rc=2
+            fi
+        fi
+    return $rc
+}
+
+
    currtime=$(date +'%s')
    dc=$(crmadmin -q -D 2>/dev/null )
    if [ $? -eq 0 ]; then
@@ -85,17 +125,19 @@ function get_and_print_node()
        (( count++ ))
    done
 
-    if [ $count -eq 2 ]; then
-       if [ ${ALpt[0]} -gt ${ALpt[1]} ]; then
+   lpa_check_lpt_status; rc=$?
+   case "$rc" in
+       0 )
           echo "==> ${ANodes[0]} wins LPA"
-       fi
-       if [ ${ALpt[1]} -gt ${ALpt[0]} ]; then
+           ;;
+       1 )
           echo "==> ${ANodes[1]} wins LPA"
-       fi
-       if [ ${ALpt[1]} -eq ${ALpt[0]} ]; then
+           ;;
+       2 )
           echo "==> ${ANodes[0]} / ${ANodes[1]} LPA stalemate"
-       fi
-    fi
-   
-   
-   # ptest -sL | grep promo 
+           ;;
+       * )
+          echo "==> LPA FAILURE!!"
+           ;;
+   esac
+
