SQL query and cluster attributes query changed to support chains

diff --git a/SAPHana/SAPHana b/SAPHana/SAPHana
--- a/SAPHana/SAPHana
+++ b/SAPHana/SAPHana
@@ -132,7 +132,7 @@ function saphana_meta_data() {
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="SAPHana">
-<version>0.149.1</version>
+<version>0.149.2</version>
 
 <shortdesc lang="en">Manages two SAP HANA instances in system replication (SR).</shortdesc>
 <longdesc lang="en">
@@ -562,8 +562,9 @@ function saphana_init() {
     #
     DUPLICATE_PRIMARY_TIMEOUT="${OCF_RESKEY_DUPLICATE_PRIMARY_TIMEOUT:-7200}"
     super_ocf_log debug "DBG: DUPLICATE_PRIMARY_TIMEOUT=$DUPLICATE_PRIMARY_TIMEOUT"
-
+    #
     # Determine list of other cluster nodes and store in otherNodes variable
+    otherNodes=()
     case $(crm_attribute --type crm_config --name cluster-infrastructure -q) in
        *openais* ) otherNodes=($(crm_node -l | awk '$3 == "member" { if ($2 != me) { print $2 }}' me=${NODENAME}));;
        *cman*    ) otherNodes=($(crm_node -l | awk '{for (i=1; i<=NF; i++) { if ($i != me) { print $i }}}' me=${NODENAME}));;
@@ -651,9 +652,13 @@ function saphana_init() {
 function check_secstore_users()
 {
     super_ocf_log info "FLOW $FUNCNAME ($*)"
-    local user=$1
+    local user=""
     local rc=1
-    $DIR_EXECUTABLE/hdbuserstore list | grep -q "KEY $user" && rc=0
+    while [ $# -gt 0 ]; do
+        user="$1"
+        $DIR_EXECUTABLE/hdbuserstore list | grep -q "KEY $user" && echo "$user" && rc=0
+        shift
+    done
     super_ocf_log info "FLOW $FUNCNAME rc=$rc"
     return $rc
 }
@@ -796,26 +801,30 @@ function analyze_hana_sync_status()
     local vHost=""
     local n=""
     local hana_sync_status="" what_does_the_chamelion_say=""
-    local secUser="slehaLoc"
+    local secUser="SLEHALOC"
     local chkusr;
     local rc=0
     local sqlrc=0
-    local query_state='select distinct REPLICATION_STATUS from SYS.M_SERVICE_REPLICATION'
+# local query_state='select distinct REPLICATION_STATUS from SYS.M_SERVICE_REPLICATION'
+# select distinct REPLICATION_STATUS from SYS.M_SERVICE_REPLICATION where SITE_NAME='"SITE1"'"
+    local query_state="select distinct REPLICATION_STATUS from SYS.M_SERVICE_REPLICATION where SITE_NAME='"${sr_name}"'"
     local query_secondaries='select distinct  SECONDARY_HOST from SYS.M_SERVICE_REPLICATION'
     local query_failed_secondaries="select distinct SECONDARY_HOST from SYS.M_SERVICE_REPLICATION  where SECONDARY_SITE_NAME = (select distinct  SECONDARY_SITE_NAME from SYS.M_SERVICE_REPLICATION WHERE REPLICATION_STATUS != 'ACTIVE')"
     local all_cluster_hosts all_secondary_hosts all_broken_secondaries
-    # TODO: PRIO4: remove check_secstore_users later
-    check_secstore_users SLEHALOC; chkusr=$?
+#
+#####################################################################################################
+#
+# select distinct SITE_NAME, HOST, REPLICATION_STATUS, SECONDARY_SITE_NAME, SECONDARY_HOST from SYS.M_SERVICE_REPLICATION
+#
+# ===> "Walldorf", "sap-app-8"  "ACTIVE", "Rot",  "sap-app-5"
+#      "Rot",      "sap-app-5", "ACTIVE", "oslo", "sap-app-7"
+#
+#####################################################################################################
+#
+    secUser=$(check_secstore_users SLEHALOC SAPHANASR RHELHALOC) ; chkusr=$?
     if [ $chkusr -ne 0 ]; then
-         check_secstore_users RHELHALOC; chkusr=$?
-         if [ $chkusr -ne 0 ]; then
-              super_ocf_log err  "ACT: Secure store users are missing (see best practice manual how to setup the users)"
-              rc=$OCF_ERR_CONFIGURED
-         else
-             secUser="RHELHALOC"
-         fi
-    else
-         secUser="SLEHALOC"
+        super_ocf_log err  "ACT: Secure store users are missing (see best practice manual how to setup the users)"
+        rc=$OCF_ERR_CONFIGURED
     fi
     hana_sync_status=$(timeout 60 $DIR_EXECUTABLE/hdbsql -a -x -U $secUser  $query_state); sqlrc=$?
     hana_sync_status=$(echo $hana_sync_status | dequote)
@@ -1727,7 +1736,6 @@ function saphana_monitor_primary()
                         analyze_hana_sync_status
                         ;;
                 esac
-                ## begin fix bnc#892466 - MGFH ########################
                 rem_role=$(get_hana_attribute ${remoteHost} ${ATTR_NAME_HANA_ROLES[@]})
                 rem_clone_status=$(get_hana_attribute ${remoteHost} ${ATTR_NAME_HANA_CLONE_STATE[@]})
                 if [ "$promote_attr" = "DEMOTED" -a "$rem_clone_status" = "PROMOTED" ]; then
@@ -1743,7 +1751,6 @@ function saphana_monitor_primary()
                           ;;
                    esac
                 fi
-                ## end  fix bnc#892466 - MGFH ########################
                 scoring_crm_master "$my_role" "$my_sync"
             fi
             ;;
@@ -1767,7 +1774,7 @@ function saphana_monitor_primary()
 # function: saphana_monitor_secondary - monitor a hana clone instance
 # params:   -
 # globals:  OCF_*, ATTR_NAME_*, NODENAME
-# saphana_monitor_secondary #
+# saphana_monitor_secondary
 #
 function saphana_monitor_secondary()
 {
