Improved lpa_check_lpt_status to handle both REAL lpts and initial values

diff --git a/SAPHana/SAPHana b/SAPHana/SAPHana
--- a/SAPHana/SAPHana
+++ b/SAPHana/SAPHana
@@ -180,7 +180,7 @@ function saphana_meta_data() {
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="SAPHana">
-<version>0.102.2014.03.20.1</version>
+<version>0.103.2014.03.20.2</version>
 
 <shortdesc lang="en">Manages a SAP HANA instance.</shortdesc>
 <longdesc lang="en">
@@ -1400,8 +1400,8 @@ function saphana_start_primary()
                     check_for_primary; primary_status=$?
                     if [ $primary_status -eq $HANA_STATE_SECONDARY ]; then
                         super_ocf_log info "fhACT: Register successful"
-                        lpa_push_lpt 1
-                        lpa_set_lpt  1
+                        lpa_push_lpt 10
+                        lpa_set_lpt  10
                         set_crm_master  0
                         saphana_start_secondary
                         rc=$?
@@ -1509,8 +1509,8 @@ function saphana_start_secondary()
     #
     ####### LPA - begin
     #
-    lpa_push_lpt 1
-    lpa_set_lpt  1
+    lpa_push_lpt 10
+    lpa_set_lpt  10
     # 
     ####### LPA - end
     # 
@@ -1703,10 +1703,10 @@ function lpa_init_lpt() {
     LPTloc=$(lpa_get_lpt ${HOSTNAME}) || LPTloc=$(lpa_pull_lpt) || \
         if   [ "$hana_state" -eq "$HANA_STATE_PRIMARY" ];  then    # Initialize for Primary
             # init primary
-            lpa_push_lpt "2"; rc=$?
+            lpa_push_lpt "20"; rc=$?
         elif [ "$hana_state" -eq "$HANA_STATE_SECONDARY" ]; then   # Initialize for Secondary
             # init secondary
-            lpa_push_lpt "1"; rc=$?
+            lpa_push_lpt "10"; rc=$?
         else
             rc=2                                   
         fi
@@ -1722,78 +1722,74 @@ function lpa_init_lpt() {
 # lpa_check_lpt_status
 #
 # Returncodes:
-#    rc=0: LPA-PRIMARY-STARTUP, rc=1: LPA-SECONDARY-REGISTER, rc=2: LPA-WAITING, rc=3: LPA-FATAL
 #
 # Initializing (if NO local LPT-file):
-#    SECONDARY sets to 0
-#    PRIMARY   sets to 1
-# 
-# - 0: If LPTlocal > LPTremote ==> we have win the race => STARTUP
-# - 0: If undef LPTlocal and LPTremote=0  ==> STARTUP
-# - 1: If LPTlocal < LPTremote ==> we lost race => REGISTER
-# - 2: If undef(=-1) LPTremote ==> WAITING  ==> would mean also MONITORS need to do something...
-# - 3: If LPTlocal = LPTremote = 1 ==> we are FAILING - to SECONDARIES!!
-# - 3: If LPTlocal = LPTremote != 1 ==> we are FAILING - to PRIMARIES and no valid LPT to decide on both nodes!!
-# - 4: Something really went wrong           
+#    SECONDARY sets to 10
+#    PRIMARY   sets to 20
 #
+#### NEW (TODO PRIO1)
+#
+#    LPRlocal OR LPTremore ARE real lpt (>1000)
+#        THEN:
+#            Bigger LPR wins, if delta-gab is OK
+#               LPTlocal >> LPTremore ===> rc=0 (start) 
+#               LPTRemote >> LPTlocal ===> rc=1 (register)
+#            Stalemate in all other cases ==> STALEMATE-HANDLING ===> rc=2 (wait)
+#    LPRlocal AND LPTremore ARE NOT real lpt (<=1000)
+#        THEN:
+#            Bigger LPT wins
+#               LPTlocal > LPTremore ===> rc=0 (start) 
+#               LPTRemote > LPTlocal ===> rc=1 (register)
+#            Stalemate in all other cases ==> STALEMATE-HANDLING ===> rc=2 (wait)
+#    LPTRemote is not initialized (0)
+#        THEN:
+#            WAIT ==> like STALEMATE-HANDLING ===> rc=2 (wait)
+#    
 function lpa_check_lpt_status() {
     super_ocf_log info "fhFLOW function: $FUNCNAME $1 $2 $3 $4"
     local rc=0
     local LPTloc=-1
     local LPTrem=-1
-    local LPTDiff=0
+    local LPTMark=1000
+    local delta=0
     #
-    # First fetch LPT from cluster attributes
+    # First GET LPT from ATTR-FILE-DEFAULT
     #
-    LPTloc=$(lpa_get_lpt $HOSTNAME); lparc=$?
+    LPTloc=$(lpa_get_lpt $HOSTNAME); lparc=$?   # ATTR
     if [ "$lparc" -ne 0 ]; then
         # as a fallback try to fetch the value from external status file
-        LPTloc=$(lpa_pull_lpt); 
+        LPTloc=$(lpa_pull_lpt);                 # FILE
         lparc=$?
         if [ -z "$LPTloc" -o "$LPTloc" -eq -1 -o "$lparc" -ne 0 ]; then
             # last option - try to initialize as PRIMARY
-            lpa_push_lpt 2
-            lpa_set_lpt  2
-            LPTloc=2
+            lpa_push_lpt 20
+            lpa_set_lpt  20
+            LPTloc=20                           # DEFAULT
         fi
     fi
-#
-# TODO: PRIO2: How to handle situations where we still do not know "the" remoteHost - should
-#       we just scan for all remoteHosts (shell array)?
-#
     LPTrem=$(lpa_get_lpt $remoteHost); lparc=$?
     if [ $lparc -ne 0 ]; then
         # LPT of the other node could not be evaluated - LPA says WAIT
         super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc, LPTrem undefined => WAIT"
         rc=2
     else
-        #
-        # TODO: PRIO1: Maybe LPA should also say win, if lpa-loc=2 and lpa-rem=1 (as special init case)
-        #
-        (( LPTDiffLoc = LPTloc - LPTrem ))
-        (( LPTDiffRem = LPTrem - LPTloc ))
-        if [ $LPTDiffLoc -gt $DUPLICATE_PRIMARY_TIMEOUT ]; then 
+        if [ $LPTloc -lt $LPTMark -a $LPTrem -lt $LPTMark ]; then
+           delta=0   # both lpts are not a real timestamp so just take the greater one
+        else
+           delta=$DUPLICATE_PRIMARY_TIMEOUT   # at least one of the lpts is a real timestamp so include delta-gap
+        fi
+        if (( delta < LPTloc - LPTrem )); then 
             # We are the winner - LPA says STARTUP
-            super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc >> LPTrem=$LPTrem => START"
+            super_ocf_log info "fhDBG: LPA: LPTloc wins $LPTloc > $LPTrem + $delta => START"
             rc=0
-        elif [ $LPTDiffRem -gt $DUPLICATE_PRIMARY_TIMEOUT ]; then 
+        elif (( delta < LPTRem - LPTloc )); then 
             # The other one has won - LPA says REGISTER
-            super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc << LPTrem=$LPTrem => REGISTER"
+            super_ocf_log info "fhDBG: LPA: LPTrem wins $LPTrem > $LPTrem + $delta => REGISTER"
             rc=1
         else                                     
-            if [ $LPTloc -eq 1 ]; then
-                # TODO: PRIO1: Do we need to differ between a 1=1 with different sync status?
-                # This case can happen: a) when really to secondaries would in the cluster 
-                #                       b) when a primary failed and restarts with prefrred remote takeover 
-                #                        
-                super_ocf_log info "fhDBG: LPA: Both LPTloc=$LPTloc and LPTrem=$LPTrem => WAIT"
-                rc=2
-            else
-                # THIS IS A STALEMATE, WHICH COULD HAPPEN
-                # TODO: PRIO1: CHeck, if FAIL is the correct behaviour - or just wait for admin to decide via attribute?
-                super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc == LPTrem=$LPTrem => WAIT"
-                rc=2
-            fi
+            super_ocf_log info "fhDBG: LPA: Difference between LPTloc and LPTrem is less than delta ($delta) => WAIT"
+            # TODO: PRIO1: ADD STALEMATE-HANDLING HERE
+            rc=2
         fi        
     fi    
     super_ocf_log info "fhFLOW $FUNCNAME  -> return code = $rc"
@@ -1979,29 +1975,29 @@ function saphana_monitor_primary()
                         remoteSync=$(get_hana_sync_status_attr $remoteHost)
                         case "$remoteSync" in
                             SOK )
-                                 super_ocf_log info "fhDEC: PreferSiteTakeover selected so decrease promotion score here"
+                                 super_ocf_log info "fhDEC: PreferSiteTakeover selected so decrease promotion score here (and reset lpa)"
                                  set_crm_master 5
-                                 # TODO: PRIO1: CHECK, IF lpa_set_lpt 1 IS CORRECT HERE 
-                                 #       - IS IT BETTER TO SET lpa_set_lpt 2?
-                                 #       1. lpa_set_lpt 1
-                                 #       - Problem is, if BOTH hana sites failed, but remoteSync is still SOK than I get a lpa 1-1 situation
-                                 #       2. lpa_set_lpt 2:
+                                 # TODO: PRIO1: CHECK, IF lpa_set_lpt 10 IS CORRECT HERE 
+                                 #       - IS IT BETTER TO SET lpa_set_lpt 20?
+                                 #       1. lpa_set_lpt 10
+                                 #       - Problem is, if BOTH hana sites failed, but remoteSync is still SOK than I get a lpa 10-10 situation
+                                 #       2. lpa_set_lpt 20:
                                  #       a) both instances are failing:
-                                 #          both clones been restarted coming up with lpa 2-1 -> local wins which is OK
+                                 #          both clones been restarted coming up with lpa 20-10 -> local wins which is OK
                                  #       b) only former primary failed:
                                  #          former primary restarted and former secondary promoted (sequence not sure!)
-                                 #          b1) primary coming up first -> lpa 2-1 -> This would be WRONG!!
-                                 #          b2) secondary promted first -> lpa 2-lpt -> former secondary wins which is OK
+                                 #          b1) primary coming up first -> lpa 20-10 -> This would be WRONG!!
+                                 #          b2) secondary promted first -> lpa 20-lpt -> former secondary wins which is OK
                                  #       3. lpa_set_lpt UNTUCHED (lpt)
                                  #       a) both instances are failing:
-                                 #          both clones been restarted and coming up with lpa lpt-1 -> local wins which is OK
+                                 #          both clones been restarted and coming up with lpa lpt-10 -> local wins which is OK
                                  #       b) only former primary failed:
                                  #          former primary restarted and former secondary promoted (sequence not sure!)
-                                 #          b1) primary coming up first -> lpa lpt-1 -> This would be WRONG!!
+                                 #          b1) primary coming up first -> lpa lpt-10 -> This would be WRONG!!
                                  #          b2) secondary promted first -> lpa lpt1-lpt2 -> former primary will wait until gab is closed
                                  #       
                                  #
-                                 lpa_set_lpt 1
+                                 lpa_set_lpt 10
                                  ;;
                             SFAIL )
                                  super_ocf_log info "fhDEC: PreferSiteTakeover selected BUT remoteHost is not in sync (SFAIL) -> local restart preferred"                            
@@ -2092,8 +2088,8 @@ function saphana_monitor_secondary()
     #    
     #### LPA begin
     #
-    lpa_set_lpt  1
-    lpa_push_lpt 1
+    lpa_set_lpt  10
+    lpa_push_lpt 10
     #
     #### LPA end
     #
@@ -2214,6 +2210,9 @@ function saphana_monitor_clone() {
 	local rc=$OCF_ERR_GENERIC
 	local promoted=0
     local init_attribute=0
+
+
+    lpa_check_lpt_status  # TODO: PRIO3 : remove that line later - its only to call lpa_check_lpt_status much more often for checking
 
 	if ocf_is_probe; then
 		super_ocf_log info "fhDBG: PROBE ONLY"
