LPA - Implementation step one - LPA functions are available but do (so far) not trigger the decission - that is the second step

diff --git a/SAPHana/SAPHana b/SAPHana/SAPHana
--- a/SAPHana/SAPHana
+++ b/SAPHana/SAPHana
@@ -122,7 +122,7 @@ function saphana_meta_data() {
 <?xml version="1.0"?>
 <!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
 <resource-agent name="SAPHana">
-<version>0.56.2014.01.23.2</version>
+<version>0.57.2014.01.24.1</version>
 
 <shortdesc lang="en">Manages a SAP HANA instance.</shortdesc>
 <longdesc lang="en">
@@ -397,6 +397,7 @@ function set_hana_clone_state()
 # globals:  meta_notify_master_uname(w), remote_sql(w), HANA_SR_TOLOPOGY(w), sr_name(w), remoteHost(w) 
 # globals:  ATTR_NAME_HANA_SYNC_STATUS(w), ATTR_NAME_HANA_PRIMARY_AT(w), ATTR_NAME_HANA_CLONE_STATE(w)
 # globals:  DIR_EXECUTABLE(w), SAPSTARTSRV(w), SAPCONTROL(w), DIR_PROFILE(w), SAPSTARTPROFILE(w), LD_LIBRARY_PATH(w), PATH(w)
+# globals:  LPA_DIRECTORY(w)
 # saphana_init : Define global variables with default values, if optional parameters are not set
 #
 #
@@ -416,6 +417,9 @@ function saphana_init() {
     PreferSiteTakeover="$OCF_RESKEY_PREFER_SITE_TAKEOVER"
     meta_notify_master_uname="$OCF_RESKEY_CRM_meta_notify_master_uname"
 
+    LPA_DIRECTORY=/var/lib/SAPHanaRA
+    LPA_ATTR=lpa_${sid}_lpt
+    # TODO: Do we still need HANA_SERVICE_ADDRESS as we now have secstore.users?
     remote_sql=$OCF_RESKEY_HANA_SERVICE_ADDRESS
 
     HANA_SR_TOPOLOGY=$OCF_RESKEY_HANA_SR_TOPOLOGY
@@ -1255,11 +1259,31 @@ function saphana_start_primary()
 	local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
     local lsrc sqlrc;
     local rc=0
+    local lpa_dec=4
     #
     # we will be a master (PRIMARY) so checking, if the is an OTHER master
     #
     super_ocf_log info "fhDBG: saphana_start_clone - check_for_primary reports HANA_STATE_PRIMARY"
 # WORKING-ZONE
+    #
+    ##### LPA beg
+    # 
+    lpa_check_lpt_status; lpa_dec=$?
+    case "$lpa_dec" in
+        0 ) # LPA says start-up
+            ;;
+        1)  # LPA says register!
+            ;;
+        2)  # LPA says wait for second LPT
+            ;;
+        3 | 4 ) # LPA says something is completely wrong - FAIL resource
+            ;;
+        * ) # LPA failed with an unkonown status - FAIL resource
+            ;;
+    esac
+    #
+    ##### LPA end
+    #
     get_hana_landscape_status; lsrc=$?
     saphana_hdbsql_check remote; sqlrc=$?
     # TODO: Include also check for remote attribute for primary status (DEMOTED/PROMOTED)
@@ -1371,6 +1395,14 @@ function saphana_start_secondary()
 	local primary_status sync_attr score_master rc=$OCF_NOT_RUNNING
     local lsrc sqlrc;
     #
+    ####### LPA - begin
+    #
+    lpa_push_lpt 1
+    lpa_set_lpt 1
+    #
+    ####### LPA - end
+    # 
+    #
     # we would be slave (secondary)
     # we first need to check, if there are Master Nodes, because the Scecondary only starts
     # successfuly, if the Primary is available. Thatfore we mark the Secondary as "WAITING"
@@ -1425,6 +1457,226 @@ function saphana_start_secondary()
     super_ocf_log info "$FUNCNAME  -> return code = $rc"
     return $rc
 }
+
+#
+############################### LPA / LPT functions -BEGIN
+#
+
+#
+# function: lpa_get_lpt - get lpt from cluster
+# params:   NODE
+# globals:  LPA_ATTR(r), TBD
+# output:   LPT
+# rc:       rc=0: OK, rc=1: TBD, rc=2: ERROR
+#
+function lpa_get_lpt() {
+    super_ocf_log info "* function: $FUNCNAME $1 $2 $3 $4"
+    local rc=1
+    local node=$1
+    local lpt=-1
+    local readrest=0
+    local lpa_file=$LPA_DIRECTORY/lpa_${sid}_${HOSTNAME}
+    #
+    # TODO: Implement lpa_get_lpt
+    #
+    crm_attribute -G -n "$LPA_ATTR" -q; rc=$?
+    if [ -n "$lpt" ]; then
+        rc=1
+        echo $lpt
+    else
+        rc=2
+    fi
+    super_ocf_log info "$FUNCNAME  -> return code = $rc"
+    return $rc    
+}
+
+#
+# function: lpa_set_lpt - set lpt in cluster
+# params:   LPT
+# globals:  LPA_ATTR(r), TBD
+# rc:       rc=0: OK, rc=1: TBD, rc=2: ERROR
+#
+function lpa_set_lpt() {
+    super_ocf_log info "* function: $FUNCNAME $1 $2 $3 $4"
+    local rc=1
+    local crm_rc=1
+    local lpt=$1
+    local clpt=-1
+    #
+    # TODO: Implement lpa_set_lpt
+    #
+    crm_attribute -v "$lpt" -n "$LPA_ATTR" -l reboot; crm_rc=$?
+    clpt=$(lpa_get_lpt $HOSTNAME)
+    if [ "$lpt" != "$clpt" ]; then
+        rc=2
+    else
+        rc=0
+    fi
+    super_ocf_log info "$FUNCNAME  -> return code = $rc"
+    return $rc    
+}
+
+#
+# function: lpa_pull_lpt - fetch lpt from file
+# params:   TBD
+# globals:  LPA_DIRECTORY(r)
+# output:   LPT
+# rc:       rc=0: OK, rc=1: TBD, rc=2: ERROR
+#
+function lpa_pull_lpt() {
+    super_ocf_log info "* function: $FUNCNAME $1 $2 $3 $4"
+    local rc=1
+    local lpt=-1
+    local readrest=0
+    local lpa_file=$LPA_DIRECTORY/lpa_${sid}_${HOSTNAME}
+    #
+    # TODO: Implement lpa_pull_lpt
+    read lpt readrest <<<$(cat $lpa_file) # exactly load first word from file to lpt
+    if [ -n "$lpt" ]; then
+        rc=1
+        echo $lpt
+    else
+        rc=2
+    fi
+    super_ocf_log info "$FUNCNAME  -> return code = $rc"
+    return $rc    
+}
+
+#
+# function: lpa_push_lpt - put lpt to file
+# params:   LPT
+# globals:  LPA_DIRECTORY(r)
+# output:   --
+# rc:       rc=0: OK, rc=1: TBD, rc=2: ERROR
+#
+function lpa_push_lpt() {
+    super_ocf_log info "* function: $FUNCNAME $1 $2 $3 $4"
+    local lpt=$1
+    local clpt=-1
+    local rc=1
+    local lpa_file=$LPA_DIRECTORY/lpa_${sid}_${HOSTNAME}
+    #
+    # TODO: Implement lpa_push_lpt
+    # HANA_STATE_PRIMARY
+    mkdir -p $LPA_DIRECTORY
+    echo "$lpt" > $lpa_file
+    clpt=$(lpa_pull_lpt); $lpt_rc=$?
+    if [ "$clpt" != "$lpt" -o "$lpt_rc" -ne 0 ]; then
+        rc=2
+    else
+        rc=0
+    fi     
+    super_ocf_log info "$FUNCNAME  -> return code = $rc"
+    return $rc    
+}
+
+#
+# function: lpa_init_lpt - initialize local lpt 
+# params:   HANA_STATE
+# globals:  HANA_STATE_*(r), LPA_DIRECTORY(r), sid(r), HOSTNAME(r), TBD
+# lpa_init_lpt
+#
+# Returncodes:
+#    rc=0: OK,  rc=1 TBD,  rc=2: ERROR
+#
+# Initializing (if NO local LPT-file):
+#    SECONDARY sets to 0
+#    PRIMARY   sets to 1
+# 
+function lpa_init_lpt() {
+    super_ocf_log info "* function: $FUNCNAME $1 $2 $3 $4"
+    local rc=1
+    local LPTloc=-1
+    local LPTrem=-1
+    local hana_state=$1
+    local lpa_file=$LPA_DIRECTORY/lpa_${sid}_${HOSTNAME}
+    #
+    # TODO: Implement lpa_init_lpt
+    #
+    mkdir -p $LPA_DIRECTORY
+    if   [ "$hana_state" -eq "$HANA_STATE_PRIMARY" ];  then    # Initialize for Primary
+        # init primary
+        lpa_push_lpt "2; rc=$?
+    elif [ "$hana_state" -eq "$HANA_STATE_SECONDARY" ]; then   # Initialize for Secondary
+        # init secondary
+        lpa_push_lpt "0"; rc=$?
+    else
+        rc=2                                   
+    fi
+    super_ocf_log info "$FUNCNAME  -> return code = $rc"
+    return $rc    
+}
+
+#
+# function: lpa_check_lpt_status - start a hana clone instance
+# params:   TBD
+# globals:  TBD
+# lpa_check_lpt_status
+#
+# Returncodes:
+#    rc=0: LPA-PRIMARY-STARTUP, rc=1: LPA-SECONDARY-REGISTER, rc=2: LPA-WAITING, rc=3: LPA-FATAL
+#
+# Initializing (if NO local LPT-file):
+#    SECONDARY sets to 0
+#    PRIMARY   sets to 1
+# 
+# - 0: If LPTlocal > LPTremote ==> we have win the race => STARTUP
+# - 0: If undef LPTlocal and LPTremote=0  ==> STARTUP
+# - 1: If LPTlocal < LPTremote ==> we lost race => REGISTER
+# - 2: If undef(=-1) LPTremote ==> WAITING  ==> would mean also MONITORS need to do something...
+# - 3: If LPTlocal = LPTremote = 1 ==> we are FAILING - to SECONDARIES!!
+# - 3: If LPTlocal = LPTremote != 1 ==> we are FAILING - to PRIMARIES and no valid LPT to decide on both nodes!!
+# - 4: Something really went wrong           
+#
+function lpa_check_lpt_status() {
+    super_ocf_log info "* function: $FUNCNAME $1 $2 $3 $4"
+    local rc=0
+    local LPTloc=-1
+    local LPTrem=-1
+    #
+    # TODO: Implement lpa_check_lpt_status
+    #
+    # First fetch LPT from cluster attributes
+    #
+    LPTloc=$(lpa_get_lpt $HOSTNAME); lparc=$?
+    if [ -z "$LPTloc" -o "$LPTloc" -eq -1 -o "$lparc" -ne 0 ]; then
+        # as a fallback try to fetch the value from external status file
+        LPTloc=$(lpa_pull_lpt); 
+        lparc=$?
+        if [ -z "$LPTloc" -o "$LPTloc" -eq -1 -o "$lparc" -ne 0 ]; then
+            # last option - try to initialize as PRIMARY
+            lpa_push_lpt 2
+            lpa_set_lpt  2
+            LPTloc=2
+        fi
+    fi
+    LPTrem=$(lpa_get_lpt $remoteHost); lparc=$?
+    if [ -z "$LPTlrem" -o "$LPTrem" -eq -1 -o "$lparc" -ne 0 ]; then
+        # LPT of the other node could not be evaluated - LPA says WAIT
+        super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc, LPTrem undefined => WAIT"
+        rc=2
+    else
+        if [ $LPTloc -gt $LPTrem ]; then 
+            # We are the winner :) - LPA says STARTUP
+            super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc > LPTrem=$LPTrem => START"
+            rc=0
+        elif [ $LPTloc -lt $LPTrem ]; then 
+            # The other one has won :( - LPA says REGISTER
+            super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc < LPTrem=$LPTrem => REGISTER"
+            rc=1
+        else                                     
+            # OhOh - That should not happen :/ - LPA says FAIL!
+            super_ocf_log info "fhDBG: LPA: LPTloc=$LPTloc == LPTrem=$LPTrem => FAIL"
+            rc=3
+        fi        
+    fi    
+    super_ocf_log info "$FUNCNAME  -> return code = $rc"
+    return $rc    
+}
+
+#
+############################### LPA / LPT functions - END
+#
 
 #
 # function: saphana_start_clone - start a hana clone instance
@@ -1503,10 +1755,21 @@ function saphana_monitor_primary()
 	local rc=$OCF_ERR_GENERIC
 	local promoted=0
     local init_attribute=0
+    local LPTloc=-1
     #
     # OK, we are running as HANA PRIMARY
     #
     super_ocf_log info "fhDBG saphana_monitor_clone: HANA_STATE_PRIMARY"
+    
+    #
+    #### LPA begin
+    #
+    LPTloc=$(date '+%s')
+    lpa_set_lpt $LPTloc
+    lpa_push_lpt $LPTloc
+    #
+    #### LPA end
+    #
     #
     ##### CHECK, IF WE ARE DEMOTED (CLUSTER NODE ATTRIBUTE)
     #
@@ -1613,6 +1876,13 @@ function saphana_monitor_secondary()
     local init_attribute=0
     #
     # OK, we are running as HANA SECONDARY (or even not as PRIMARY)
+    #    
+    #### LPA begin
+    #
+    lpa_set_lpt  1
+    lpa_push_lpt 1
+    #
+    #### LPA end
     #
     ##### CHECK, IF WE ARE DEMOTED (CLUSTER NODE ATTRIBUTE)
     #
